execution:
    uuid: 4eb2bc95-7c7c-4c38-9294-82153c24373b
    runtime:
        start: 2019-07-30T23:13:47.950978-05:00
        end: 2019-07-30T23:44:24.069672-05:00
        duration: 30 minutes, 36 seconds, and 118694 microseconds

action:
    type: import
    format: PairedEndFastqManifestPhred33V2
    manifest:
    -   name: manifest.tsv
        md5sum: 436c730834505a696e7cf568dd9ece97

transformers:
    output:
    -   from: PairedEndFastqManifestPhred33V2
        to: SingleLanePerSamplePairedEndFastqDirFmt
        plugin: !ref 'environment:plugins:types'

environment:
    platform: linux-x86_64
    python: |-
        3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38)
        [GCC 7.3.0]
    framework:
        version: 2019.4.0
        website: https://qiime2.org
        citations:
        - !cite 'framework|qiime2:2019.4.0|0'
    plugins:
        types:
            version: 2019.4.1
            website: https://github.com/qiime2/q2-types
    python-packages:
        xopen: 0.5.1
        widgetsnbextension: 3.4.2
        wheel: 0.33.1
        webencodings: 0.5.1
        wcwidth: 0.1.7
        urllib3: 1.24.2
        unifrac: 0.9.2
        tzlocal: 1.5.1
        traitlets: 4.3.2
        tornado: 6.0.2
        testpath: 0.4.2
        terminado: 0.8.2
        statsmodels: 0.9.0
        six: 1.12.0
        setuptools: 41.0.1
        Send2Trash: 1.5.0
        seaborn: 0.9.0
        scipy: 1.2.1
        scikit-learn: 0.20.2
        scikit-bio: 0.5.5
        requests: 2.21.0
        qiime2: 2019.4.0
        q2templates: 2019.4.0
        q2cli: 2019.4.0
        q2-vsearch: 2019.4.0
        q2-types: 2019.4.1
        q2-taxa: 2019.4.0
        q2-sample-classifier: 2019.4.0
        q2-quality-filter: 2019.4.0
        q2-quality-control: 2019.4.0
        q2-phylogeny: 2019.4.0
        q2-metadata: 2019.4.0
        q2-longitudinal: 2019.4.0
        q2-gneiss: 2019.4.0
        q2-fragment-insertion: 2019.4.0
        q2-feature-table: 2019.4.0
        q2-feature-classifier: 2019.4.0
        q2-emperor: 2019.4.0
        q2-diversity: 2019.4.0
        q2-demux: 2019.4.1
        q2-deblur: 2019.4.0
        q2-dada2: 2019.4.0
        q2-cutadapt: 2019.4.0
        q2-composition: 2019.4.0
        q2-alignment: 2019.4.0
        pyzmq: 18.0.1
        PyYAML: 5.1.1
        pytz: '2019.1'
        python-dateutil: 2.8.0
        pytest: 4.4.2
        PySocks: 1.6.8
        pyrsistent: 0.15.1
        pyparsing: 2.3.0
        pyOpenSSL: 19.0.0
        Pygments: 2.4.0
        pycparser: '2.19'
        py: 1.8.0
        ptyprocess: 0.6.0
        psutil: 5.6.2
        prompt-toolkit: 2.0.9
        prometheus-client: 0.6.0
        pluggy: 0.11.0
        pip: 19.1.1
        Pillow: 6.0.0
        pickleshare: 0.7.5
        pexpect: 4.7.0
        patsy: 0.5.1
        parso: 0.4.0
        pandocfilters: 1.4.2
        pandas: 0.24.2
        packaging: '19.0'
        olefile: '0.46'
        numpy: 1.16.2
        notebook: 5.7.8
        nose: 1.3.7
        networkx: '2.3'
        nbformat: 4.4.0
        nbconvert: 5.5.0
        natsort: 6.0.0
        msgpack: 0.6.1
        more-itertools: 4.3.0
        mistune: 0.8.4
        matplotlib: 3.0.3
        MarkupSafe: 1.1.1
        lockfile: 0.12.2
        kiwisolver: 1.1.0
        jupyter-core: 4.4.0
        jupyter-client: 5.2.4
        jsonschema: 3.0.1
        Jinja2: 2.10.1
        jedi: 0.13.3
        ipywidgets: 7.4.2
        ipython: 7.5.0
        ipython-genutils: 0.2.0
        ipykernel: 5.1.0
        ijson: '2.3'
        idna: '2.8'
        hdmedians: '0.13'
        h5py: 2.9.0
        gneiss: 0.4.4
        future: 0.17.1
        fastcluster: 1.1.25
        entrypoints: '0.3'
        emperor: 1.0.0b19
        dnaio: '0.3'
        defusedxml: 0.5.0
        decorator: 4.4.0
        deblur: 1.1.0
        cycler: 0.10.0
        cutadapt: '2.3'
        cryptography: 2.6.1
        Click: '7.0'
        chardet: 3.0.4
        cffi: 1.12.3
        certifi: 2019.6.16
        CacheControl: 0.12.5
        bz2file: '0.98'
        bokeh: 1.1.0
        bleach: 3.1.0
        biom-format: 2.1.7
        bibtexparser: 1.1.0
        backcall: 0.1.0
        attrs: 19.1.0
        atomicwrites: 1.3.0
        asn1crypto: 0.24.0
